### ISSUE TITLE
Bagnon no longer Highlights un-usable items

### ISSUE THREAD

**Issue by Torsin** [icyblade/wow_addons#1]
This problem is caused by the commented out section in Unfit-1.0.lua, which stops that library from actually doing anything, functionality of the Bagnon addon (the portion that actually determines if an item is un-usable or not), this was due to the fact that GetAuctionItemSubClasses now returns numbers rather than the helpful Text Descriptions pre-Legion.  However GetItemSubClassInfo does return this info.  So with a bit of rework I believe I have this working 100% now, although it is a little less intuitive since we cannot simply assign the function, as it uses two values to return the appropriate information.

In addition I replaced the confusing numbered arrays at the top with the more descriptive WOW LE_ITEM_WEAPON_<TYPE> and LE_ITEM_ARMOR_<TYPE>, which I also included in comments with their values.

I have included the entire contents of what the file looks like on my system.

[Unfit-1.0.lua.txt](https://github.com/icyblade/wow_addons/files/358430/Unfit-1.0.lua.txt)

**Comment by icyblade** [comment]
fixed in commit [2a9678262b1fab6ee4e353acd12d4b6bee628be1](https://github.com/icyblade/wow_addons/commit/2a9678262b1fab6ee4e353acd12d4b6bee628be1)

thanks :-)
